#task2 
file1=open("output.txt",'w+')
pen=input("Enter text to write to the file: ")
file1.write(pen)
print("Data successfully written to output.txt.\n")
file1.close()
file1=open("output.txt",'a')
pen=input("Enter additional text to append: ")
file1.write("\n"+pen)
print("Data successfully appended.")
file1.close()
file1=open("output.txt",'r')
print("\nFinal content of output.txt:")
read_file=file1.read()
print(read_file)
file1.close()
